using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraBars;
using DevExpress.Utils;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraEditors.Controls;

namespace ANZ2AMLO.Forms
{
    public partial class frmGridSample : DevExpress.XtraEditors.XtraForm
    {
        RepositoryItemButtonEdit EditButton = new RepositoryItemButtonEdit();
        public frmGridSample()
        {
            InitializeComponent();
            
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new ANZ2AMLO.Contexts.AnzContextsDataContext().TableSamples;

            this.gridView1.Columns["Name"].ShowButtonMode = DevExpress.XtraGrid.Views.Base.ShowButtonModeEnum.ShowAlways;
            this.gridView1.Columns["Name"].ColumnEdit = EditButton;
            this.gridView1.Columns["Name"].OptionsColumn.ReadOnly = true;

           
                }

         void BtEvent(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)

        {
            DevExpress.XtraEditors.XtraMessageBox.Show("Click");

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
           
        }
    }
}