#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANZ2AMLO.Contexts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbanz2amlo")]
	public partial class AnzContextsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AnzContextsDataContext() : 
				base(global::ANZ2AMLO.Properties.Settings.Default.dbanz2amloConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AnzContextsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnzContextsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnzContextsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnzContextsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<unloading> unloadings
		{
			get
			{
				return this.GetTable<unloading>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.unloading")]
	public partial class unloading
	{
		
		private int _unload_id;
		
		private string _delivery;
		
		private string _item;
		
		private string _ship_to_party;
		
		private string _cus_name;
		
		private string _external_delivery_id;
		
		private string _material;
		
		private System.Nullable<int> _delivery_quantity;
		
		private string _sales_unit;
		
		private string _picking_status;
		
		private string _good_movement_stat;
		
		private string _plant;
		
		private string _description;
		
		private string _base_unit;
		
		private string _sold_to_paty;
		
		private string _purchaseing_document;
		
		private System.Nullable<System.DateTime> _good_issue_date;
		
		private System.Nullable<System.DateTime> _import_date;
		
		private System.Nullable<int> _pk_id;
		
		private string _kb_number;
		
		private System.Nullable<int> _ssa_id;
		
		private string _customer_material_number;
		
		private System.Nullable<int> _kb_id;
		
		private string _unloading_point;
		
		private System.Nullable<int> _un_doc_id;
		
		private System.Nullable<int> _ob_id;
		
		private System.Nullable<int> _unload_status;
		
		public unloading()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unload_id", DbType="Int NOT NULL")]
		public int unload_id
		{
			get
			{
				return this._unload_id;
			}
			set
			{
				if ((this._unload_id != value))
				{
					this._unload_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delivery", DbType="NChar(10)")]
		public string delivery
		{
			get
			{
				return this._delivery;
			}
			set
			{
				if ((this._delivery != value))
				{
					this._delivery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item", DbType="NChar(10)")]
		public string item
		{
			get
			{
				return this._item;
			}
			set
			{
				if ((this._item != value))
				{
					this._item = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_to_party", DbType="NChar(10)")]
		public string ship_to_party
		{
			get
			{
				return this._ship_to_party;
			}
			set
			{
				if ((this._ship_to_party != value))
				{
					this._ship_to_party = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_name", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string cus_name
		{
			get
			{
				return this._cus_name;
			}
			set
			{
				if ((this._cus_name != value))
				{
					this._cus_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_external_delivery_id", DbType="NChar(10)")]
		public string external_delivery_id
		{
			get
			{
				return this._external_delivery_id;
			}
			set
			{
				if ((this._external_delivery_id != value))
				{
					this._external_delivery_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material", DbType="NChar(25)")]
		public string material
		{
			get
			{
				return this._material;
			}
			set
			{
				if ((this._material != value))
				{
					this._material = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delivery_quantity", DbType="Int")]
		public System.Nullable<int> delivery_quantity
		{
			get
			{
				return this._delivery_quantity;
			}
			set
			{
				if ((this._delivery_quantity != value))
				{
					this._delivery_quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_unit", DbType="NChar(10)")]
		public string sales_unit
		{
			get
			{
				return this._sales_unit;
			}
			set
			{
				if ((this._sales_unit != value))
				{
					this._sales_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picking_status", DbType="NChar(5)")]
		public string picking_status
		{
			get
			{
				return this._picking_status;
			}
			set
			{
				if ((this._picking_status != value))
				{
					this._picking_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_good_movement_stat", DbType="NChar(3)")]
		public string good_movement_stat
		{
			get
			{
				return this._good_movement_stat;
			}
			set
			{
				if ((this._good_movement_stat != value))
				{
					this._good_movement_stat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plant", DbType="NChar(5)")]
		public string plant
		{
			get
			{
				return this._plant;
			}
			set
			{
				if ((this._plant != value))
				{
					this._plant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_base_unit", DbType="NChar(10)")]
		public string base_unit
		{
			get
			{
				return this._base_unit;
			}
			set
			{
				if ((this._base_unit != value))
				{
					this._base_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sold_to_paty", DbType="NChar(10)")]
		public string sold_to_paty
		{
			get
			{
				return this._sold_to_paty;
			}
			set
			{
				if ((this._sold_to_paty != value))
				{
					this._sold_to_paty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purchaseing_document", DbType="NChar(10)")]
		public string purchaseing_document
		{
			get
			{
				return this._purchaseing_document;
			}
			set
			{
				if ((this._purchaseing_document != value))
				{
					this._purchaseing_document = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_good_issue_date", DbType="Date")]
		public System.Nullable<System.DateTime> good_issue_date
		{
			get
			{
				return this._good_issue_date;
			}
			set
			{
				if ((this._good_issue_date != value))
				{
					this._good_issue_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_import_date", DbType="Date")]
		public System.Nullable<System.DateTime> import_date
		{
			get
			{
				return this._import_date;
			}
			set
			{
				if ((this._import_date != value))
				{
					this._import_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_id", DbType="Int")]
		public System.Nullable<int> pk_id
		{
			get
			{
				return this._pk_id;
			}
			set
			{
				if ((this._pk_id != value))
				{
					this._pk_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kb_number", DbType="NVarChar(10)")]
		public string kb_number
		{
			get
			{
				return this._kb_number;
			}
			set
			{
				if ((this._kb_number != value))
				{
					this._kb_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ssa_id", DbType="Int")]
		public System.Nullable<int> ssa_id
		{
			get
			{
				return this._ssa_id;
			}
			set
			{
				if ((this._ssa_id != value))
				{
					this._ssa_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_material_number", DbType="VarChar(20)")]
		public string customer_material_number
		{
			get
			{
				return this._customer_material_number;
			}
			set
			{
				if ((this._customer_material_number != value))
				{
					this._customer_material_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kb_id", DbType="Int")]
		public System.Nullable<int> kb_id
		{
			get
			{
				return this._kb_id;
			}
			set
			{
				if ((this._kb_id != value))
				{
					this._kb_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unloading_point", DbType="VarChar(10)")]
		public string unloading_point
		{
			get
			{
				return this._unloading_point;
			}
			set
			{
				if ((this._unloading_point != value))
				{
					this._unloading_point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_un_doc_id", DbType="Int")]
		public System.Nullable<int> un_doc_id
		{
			get
			{
				return this._un_doc_id;
			}
			set
			{
				if ((this._un_doc_id != value))
				{
					this._un_doc_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ob_id", DbType="Int")]
		public System.Nullable<int> ob_id
		{
			get
			{
				return this._ob_id;
			}
			set
			{
				if ((this._ob_id != value))
				{
					this._ob_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unload_status", DbType="Int")]
		public System.Nullable<int> unload_status
		{
			get
			{
				return this._unload_status;
			}
			set
			{
				if ((this._unload_status != value))
				{
					this._unload_status = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
